# ==============================================================================
# Merged Lakeflow Source: companies_house
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/companies_house/companies_house_schemas.py
    ########################################################

    AUDIT_FIELDS = [
        StructField("_ingested_at", TimestampType(), True),
        StructField("_ingested_by", StringType(), True),
        StructField("_source_api_url", StringType(), True),
        StructField("_source_record_url", StringType(), True),
    ]


    # =============================================================================
    # Reusable nested struct definitions
    # =============================================================================

    ADDRESS_STRUCT = StructType(
        [
            StructField("premises", StringType(), True),
            StructField("address_line_1", StringType(), True),
            StructField("address_line_2", StringType(), True),
            StructField("locality", StringType(), True),
            StructField("region", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("country", StringType(), True),
            StructField("care_of", StringType(), True),
            StructField("po_box", StringType(), True),
        ]
    )
    """Address struct used across profile, officers, PSC, and standalone address."""


    DATE_OF_BIRTH_STRUCT = StructType(
        [
            StructField("month", LongType(), True),
            StructField("year", LongType(), True),
        ]
    )
    """Partial DOB (privacy-restricted: no day) for natural-person officers / PSCs."""


    NAME_ELEMENTS_STRUCT = StructType(
        [
            StructField("title", StringType(), True),
            StructField("forename", StringType(), True),
            StructField("middle_name", StringType(), True),
            StructField("surname", StringType(), True),
        ]
    )


    # =============================================================================
    # company_profile
    # =============================================================================

    ACCOUNTING_REFERENCE_DATE_STRUCT = StructType(
        [
            StructField("day", LongType(), True),
            StructField("month", LongType(), True),
        ]
    )

    LAST_ACCOUNTS_STRUCT = StructType(
        [
            StructField("period_start_on", StringType(), True),
            StructField("period_end_on", StringType(), True),
            StructField("made_up_to", StringType(), True),
            StructField("type", StringType(), True),
        ]
    )

    NEXT_ACCOUNTS_STRUCT = StructType(
        [
            StructField("period_start_on", StringType(), True),
            StructField("period_end_on", StringType(), True),
            StructField("due_on", StringType(), True),
            StructField("overdue", BooleanType(), True),
        ]
    )

    ACCOUNTS_STRUCT = StructType(
        [
            StructField("accounting_reference_date", ACCOUNTING_REFERENCE_DATE_STRUCT, True),
            StructField("last_accounts", LAST_ACCOUNTS_STRUCT, True),
            StructField("next_accounts", NEXT_ACCOUNTS_STRUCT, True),
            StructField("next_due", StringType(), True),
            StructField("next_made_up_to", StringType(), True),
            StructField("overdue", BooleanType(), True),
        ]
    )

    CONFIRMATION_STATEMENT_STRUCT = StructType(
        [
            StructField("last_made_up_to", StringType(), True),
            StructField("next_due", StringType(), True),
            StructField("next_made_up_to", StringType(), True),
            StructField("overdue", BooleanType(), True),
        ]
    )

    COMPANY_PROFILE_LINKS_STRUCT = StructType(
        [
            StructField("self", StringType(), True),
            StructField("filing_history", StringType(), True),
            StructField("officers", StringType(), True),
            StructField("persons_with_significant_control", StringType(), True),
            StructField("persons_with_significant_control_statements", StringType(), True),
            StructField("charges", StringType(), True),
            StructField("insolvency", StringType(), True),
            StructField("exemptions", StringType(), True),
            StructField("registers", StringType(), True),
            StructField("overseas", StringType(), True),
            StructField("uk_establishments", StringType(), True),
        ]
    )

    PREVIOUS_COMPANY_NAME_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
            StructField("effective_from", StringType(), True),
            StructField("ceased_on", StringType(), True),
        ]
    )

    BRANCH_COMPANY_DETAILS_STRUCT = StructType(
        [
            StructField("business_activity", StringType(), True),
            StructField("parent_company_name", StringType(), True),
            StructField("parent_company_number", StringType(), True),
        ]
    )


    COMPANY_PROFILE_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("company_name", StringType(), True),
            StructField("company_status", StringType(), True),
            StructField("company_status_detail", StringType(), True),
            StructField("type", StringType(), True),
            StructField("subtype", StringType(), True),
            StructField("date_of_creation", StringType(), True),
            StructField("date_of_cessation", StringType(), True),
            StructField("jurisdiction", StringType(), True),
            StructField("sic_codes", ArrayType(StringType()), True),
            StructField("can_file", BooleanType(), True),
            StructField("has_been_liquidated", BooleanType(), True),
            StructField("has_insolvency_history", BooleanType(), True),
            StructField("has_charges", BooleanType(), True),
            StructField("has_super_secure_pscs", BooleanType(), True),
            StructField("super_secure_managing_officer_count", LongType(), True),
            StructField("is_community_interest_company", BooleanType(), True),
            StructField("registered_office_is_in_dispute", BooleanType(), True),
            StructField("undeliverable_registered_office_address", BooleanType(), True),
            StructField("last_full_members_list_date", StringType(), True),
            StructField("external_registration_number", StringType(), True),
            StructField("partial_data_available", StringType(), True),
            StructField("etag", StringType(), True),
            StructField("accounts", ACCOUNTS_STRUCT, True),
            StructField("confirmation_statement", CONFIRMATION_STATEMENT_STRUCT, True),
            StructField("registered_office_address", ADDRESS_STRUCT, True),
            StructField("links", COMPANY_PROFILE_LINKS_STRUCT, True),
            StructField(
                "previous_company_names",
                ArrayType(PREVIOUS_COMPANY_NAME_STRUCT),
                True,
            ),
            StructField("branch_company_details", BRANCH_COMPANY_DETAILS_STRUCT, True),
        ]
    )


    # =============================================================================
    # registered_office_address
    # =============================================================================

    REGISTERED_OFFICE_ADDRESS_LINKS_STRUCT = StructType(
        [
            StructField("self", StringType(), True),
        ]
    )


    REGISTERED_OFFICE_ADDRESS_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("premises", StringType(), True),
            StructField("address_line_1", StringType(), True),
            StructField("address_line_2", StringType(), True),
            StructField("locality", StringType(), True),
            StructField("region", StringType(), True),
            StructField("postal_code", StringType(), True),
            StructField("country", StringType(), True),
            StructField("care_of", StringType(), True),
            StructField("po_box", StringType(), True),
            StructField("etag", StringType(), True),
            # Envelope metadata the API returns on this endpoint.
            StructField("kind", StringType(), True),
            StructField("links", REGISTERED_OFFICE_ADDRESS_LINKS_STRUCT, True),
        ]
    )


    # =============================================================================
    # officers
    # =============================================================================

    FORMER_NAME_STRUCT = StructType(
        [
            StructField("forenames", StringType(), True),
            StructField("surname", StringType(), True),
        ]
    )

    OFFICER_IDENTIFICATION_STRUCT = StructType(
        [
            StructField("identification_type", StringType(), True),
            StructField("legal_authority", StringType(), True),
            StructField("legal_form", StringType(), True),
            StructField("place_registered", StringType(), True),
            StructField("registration_number", StringType(), True),
        ]
    )

    OFFICER_LINKS_STRUCT = StructType(
        [
            StructField(
                "officer",
                StructType(
                    [
                        StructField("appointments", StringType(), True),
                    ]
                ),
                True,
            ),
            StructField("self", StringType(), True),
        ]
    )

    # Post-ECCTA (Economic Crime and Corporate Transparency Act) identity
    # verification metadata. Present on officers whose identity has been
    # verified via an Authorised Corporate Service Provider (ACSP).
    OFFICER_IDENTITY_VERIFICATION_DETAILS_STRUCT = StructType(
        [
            StructField(
                "anti_money_laundering_supervisory_bodies",
                ArrayType(StringType()),
                True,
            ),
            StructField("appointment_verification_end_on", StringType(), True),
            StructField("appointment_verification_start_on", StringType(), True),
            StructField("appointment_verification_statement_date", StringType(), True),
            StructField("appointment_verification_statement_due_on", StringType(), True),
            StructField("authorised_corporate_service_provider_name", StringType(), True),
            StructField("identity_verified_on", StringType(), True),
            StructField("preferred_name", StringType(), True),
        ]
    )


    OFFICERS_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("name", StringType(), True),
            StructField("officer_role", StringType(), True),
            StructField("appointed_on", StringType(), True),
            StructField("resigned_on", StringType(), True),
            StructField("is_pre_1992_appointment", BooleanType(), True),
            StructField("appointed_before", StringType(), True),
            StructField("person_number", StringType(), True),
            StructField("nationality", StringType(), True),
            StructField("occupation", StringType(), True),
            StructField("country_of_residence", StringType(), True),
            StructField("responsibilities", StringType(), True),
            StructField("etag", StringType(), True),
            StructField("address", ADDRESS_STRUCT, True),
            StructField("date_of_birth", DATE_OF_BIRTH_STRUCT, True),
            StructField("former_names", ArrayType(FORMER_NAME_STRUCT), True),
            StructField("identification", OFFICER_IDENTIFICATION_STRUCT, True),
            StructField("links", OFFICER_LINKS_STRUCT, True),
            StructField(
                "identity_verification_details",
                OFFICER_IDENTITY_VERIFICATION_DETAILS_STRUCT,
                True,
            ),
        ]
    )


    # =============================================================================
    # filing_history
    # =============================================================================

    FILING_LINKS_STRUCT = StructType(
        [
            StructField("self", StringType(), True),
            StructField("document_metadata", StringType(), True),
        ]
    )

    ANNOTATION_STRUCT = StructType(
        [
            StructField("annotation", StringType(), True),
            StructField("date", StringType(), True),
            StructField("description", StringType(), True),
        ]
    )

    ASSOCIATED_FILING_STRUCT = StructType(
        [
            StructField("date", StringType(), True),
            StructField("description", StringType(), True),
            StructField("type", StringType(), True),
        ]
    )

    RESOLUTION_STRUCT = StructType(
        [
            StructField("category", StringType(), True),
            StructField("subcategory", StringType(), True),
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
            StructField("document_id", StringType(), True),
            StructField("receive_date", StringType(), True),
        ]
    )

    # ``description_values`` is a heterogeneous, description-code-specific
    # object — different filings surface different subsets of keys. Modelled
    # as an explicit struct with all observed keys (plus room for the
    # ``capital`` array-of-currency values that alterations to share capital
    # filings emit). Anything unmodelled here is silently dropped by the
    # framework's struct coercion.
    FILING_HISTORY_CAPITAL_STRUCT = StructType(
        [
            StructField("currency", StringType(), True),
            StructField("figure", StringType(), True),
        ]
    )

    FILING_HISTORY_DESCRIPTION_VALUES_STRUCT = StructType(
        [
            StructField("capital", ArrayType(FILING_HISTORY_CAPITAL_STRUCT), True),
            StructField("date", StringType(), True),
            StructField("description", StringType(), True),
            StructField("made_up_date", StringType(), True),
            StructField("new_date", StringType(), True),
            StructField("officer_name", StringType(), True),
            StructField("termination_date", StringType(), True),
        ]
    )


    FILING_HISTORY_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("transaction_id", StringType(), True),
            StructField("type", StringType(), True),
            StructField("category", StringType(), True),
            StructField("subcategory", StringType(), True),
            StructField("date", StringType(), True),
            StructField("description", StringType(), True),
            StructField("barcode", StringType(), True),
            StructField("pages", LongType(), True),
            StructField("paper_filed", BooleanType(), True),
            StructField("links", FILING_LINKS_STRUCT, True),
            StructField("annotations", ArrayType(ANNOTATION_STRUCT), True),
            StructField("associated_filings", ArrayType(ASSOCIATED_FILING_STRUCT), True),
            StructField("resolutions", ArrayType(RESOLUTION_STRUCT), True),
            # Effective date the filing acts on — often distinct from ``date``
            # (submission timestamp). Present on most filings in the live API.
            StructField("action_date", StringType(), True),
            # Description-template variables that give context to the
            # description text (e.g. officer_name for TM01 terminations,
            # made_up_date for accounts, capital for SH01 alterations).
            StructField(
                "description_values",
                FILING_HISTORY_DESCRIPTION_VALUES_STRUCT,
                True,
            ),
        ]
    )


    # =============================================================================
    # persons_with_significant_control
    # =============================================================================

    PSC_IDENTIFICATION_STRUCT = StructType(
        [
            StructField("country_registered", StringType(), True),
            StructField("legal_authority", StringType(), True),
            StructField("legal_form", StringType(), True),
            StructField("place_registered", StringType(), True),
            StructField("registration_number", StringType(), True),
        ]
    )

    PSC_LINKS_STRUCT = StructType(
        [
            StructField("self", StringType(), True),
        ]
    )


    PERSONS_WITH_SIGNIFICANT_CONTROL_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("kind", StringType(), True),
            StructField("name", StringType(), True),
            StructField("notified_on", StringType(), True),
            StructField("ceased", BooleanType(), True),
            StructField("ceased_on", StringType(), True),
            StructField("natures_of_control", ArrayType(StringType()), True),
            StructField("nationality", StringType(), True),
            StructField("country_of_residence", StringType(), True),
            StructField("description", StringType(), True),
            StructField("is_sanctioned", BooleanType(), True),
            StructField("etag", StringType(), True),
            StructField("address", ADDRESS_STRUCT, True),
            StructField("date_of_birth", DATE_OF_BIRTH_STRUCT, True),
            StructField("name_elements", NAME_ELEMENTS_STRUCT, True),
            StructField("identification", PSC_IDENTIFICATION_STRUCT, True),
            StructField("links", PSC_LINKS_STRUCT, True),
        ]
    )


    # =============================================================================
    # charges
    # =============================================================================

    CHARGE_CLASSIFICATION_STRUCT = StructType(
        [
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
        ]
    )

    CHARGE_PERSON_ENTITLED_STRUCT = StructType(
        [
            StructField("name", StringType(), True),
        ]
    )

    CHARGE_PARTICULARS_STRUCT = StructType(
        [
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
            StructField("contains_fixed_charge", BooleanType(), True),
            StructField("contains_floating_charge", BooleanType(), True),
            StructField("contains_negative_pledge", BooleanType(), True),
            StructField("floating_charge_covers_all", BooleanType(), True),
        ]
    )

    CHARGE_SECURED_DETAILS_STRUCT = StructType(
        [
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
        ]
    )

    CHARGE_TRANSACTION_LINKS_STRUCT = StructType(
        [
            StructField("filing", StringType(), True),
        ]
    )

    CHARGE_TRANSACTION_STRUCT = StructType(
        [
            StructField("filing_type", StringType(), True),
            StructField("delivered_on", StringType(), True),
            StructField("insolvency_case_number", LongType(), True),
            StructField("links", CHARGE_TRANSACTION_LINKS_STRUCT, True),
        ]
    )

    CHARGE_SCOTTISH_ALTERATIONS_STRUCT = StructType(
        [
            StructField("type", StringType(), True),
            StructField("description", StringType(), True),
            StructField("has_alterations_to_order", BooleanType(), True),
            StructField("has_alterations_to_prohibitions", BooleanType(), True),
            StructField("has_alterations_to_provisions", BooleanType(), True),
        ]
    )

    # Per-charge item envelope link. The live API returns a single ``self``
    # link pointing at the charge detail resource.
    CHARGE_LINKS_STRUCT = StructType(
        [
            StructField("self", StringType(), True),
        ]
    )


    CHARGES_SCHEMA = StructType(
        [
            StructField("company_number", StringType(), False),
            StructField("id", StringType(), True),
            StructField("charge_number", LongType(), True),
            StructField("charge_code", StringType(), True),
            StructField("status", StringType(), True),
            StructField("created_on", StringType(), True),
            StructField("delivered_on", StringType(), True),
            StructField("acquired_on", StringType(), True),
            StructField("satisfied_on", StringType(), True),
            StructField("resolved_on", StringType(), True),
            StructField("covering_instrument_date", StringType(), True),
            StructField("more_than_four_persons_entitled", BooleanType(), True),
            # Documented typo in the source API — kept literally.
            StructField("assests_ceased_released", StringType(), True),
            StructField("etag", StringType(), True),
            # The live API returns ``classification`` as a single object per
            # charge, not the array documented in the developer specification.
            # Modelled as a struct to match reality.
            StructField("classification", CHARGE_CLASSIFICATION_STRUCT, True),
            StructField("persons_entitled", ArrayType(CHARGE_PERSON_ENTITLED_STRUCT), True),
            StructField("particulars", CHARGE_PARTICULARS_STRUCT, True),
            StructField("secured_details", CHARGE_SECURED_DETAILS_STRUCT, True),
            StructField("transactions", ArrayType(CHARGE_TRANSACTION_STRUCT), True),
            StructField("scottish_alterations", CHARGE_SCOTTISH_ALTERATIONS_STRUCT, True),
            StructField("links", CHARGE_LINKS_STRUCT, True),
        ]
    )


    # =============================================================================
    # Registry maps
    # =============================================================================

    TABLE_SCHEMAS: dict[str, StructType] = {
        "company_profile": StructType(COMPANY_PROFILE_SCHEMA.fields + AUDIT_FIELDS),
        "officers": StructType(OFFICERS_SCHEMA.fields + AUDIT_FIELDS),
        "filing_history": StructType(FILING_HISTORY_SCHEMA.fields + AUDIT_FIELDS),
        "persons_with_significant_control": StructType(
            PERSONS_WITH_SIGNIFICANT_CONTROL_SCHEMA.fields + AUDIT_FIELDS
        ),
        "charges": StructType(CHARGES_SCHEMA.fields + AUDIT_FIELDS),
        "registered_office_address": StructType(REGISTERED_OFFICE_ADDRESS_SCHEMA.fields + AUDIT_FIELDS),
    }
    """Mapping of table names to their StructType schemas. Every schema has the
    ``_ingested_at`` / ``_ingested_by`` audit columns appended — see AUDIT_FIELDS."""


    TABLE_METADATA: dict[str, dict] = {
        "company_profile": {
            "primary_keys": ["company_number"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "officers": {
            # (name, appointed_on, officer_role) is not reliably unique — the
            # live API has returned two distinct appointments sharing all
            # three. _source_record_url (the item's own links.self) is the
            # API's actual resource identifier for one appointment.
            "primary_keys": ["company_number", "_source_record_url"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "filing_history": {
            "primary_keys": ["company_number", "transaction_id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "persons_with_significant_control": {
            # (notified_on, name, kind) is not reliably unique — same rationale
            # as officers above.
            "primary_keys": ["company_number", "_source_record_url"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "charges": {
            # The live API has returned charge items with a null 'id' field,
            # so (company_number, id) collides across a company's charges.
            # _source_record_url (the item's own links.self) is unique per charge.
            "primary_keys": ["company_number", "_source_record_url"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "registered_office_address": {
            "primary_keys": ["company_number"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
    }
    """Metadata for each table: primary keys, cursor field, ingestion type."""


    TABLE_ENDPOINT_PATHS: dict[str, str] = {
        "company_profile": "/company/{company_number}",
        "officers": "/company/{company_number}/officers",
        "filing_history": "/company/{company_number}/filing-history",
        "persons_with_significant_control": (
            "/company/{company_number}/persons-with-significant-control"
        ),
        "charges": "/company/{company_number}/charges",
        "registered_office_address": ("/company/{company_number}/registered-office-address"),
    }
    """URL path template per table (formatted with a ``company_number``)."""


    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())
    """Ordered list of tables exposed to LakeflowConnect.list_tables()."""


    ########################################################
    # src/databricks/labs/community_connector/sources/companies_house/companies_house.py
    ########################################################

    BASE_URL = "https://api.company-information.service.gov.uk"

    # Retry policy for HTTP 429 / 5xx responses.
    RETRIABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})
    MAX_RETRIES = 5
    INITIAL_BACKOFF_SECONDS = 1.0

    # Rate limit is 600 requests / 5-minute window (~2 req/sec).
    DEFAULT_TIMEOUT_SECONDS = 30

    # Pagination defaults for endpoints that expose start_index / items_per_page.
    DEFAULT_ITEMS_PER_PAGE = 100  # API max is 100 for filing_history; officers accepts up to 100.

    # Fallback for the ``_ingested_by`` audit column when the pipeline spec
    # doesn't pass a ``pipeline_name`` table option. There is no per-request
    # human identity inside a Spark Python Data Source worker (no dbutils, no
    # notebook user context), so this names the connector rather than a person.
    INGESTED_BY = "companies_house_lakeflow_connector"

    # Databricks SQL Statement Execution API — used only when ``company_numbers_table``
    # is configured, to look up the watchlist from a UC table instead of a static
    # connection option. Polling / retry knobs mirror the Companies House API ones.
    SQL_STATEMENT_WAIT_TIMEOUT = "30s"
    SQL_STATEMENT_POLL_SECONDS = 2.0
    SQL_STATEMENT_MAX_POLLS = 60  # 60 * 2s = 2 minutes before giving up


    class CompaniesHouseLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for Companies House UK Public Data API.

        Expected options:
            - ``api_key``: HTTP Basic Auth API key (used as username, empty password).
            - ``company_numbers``: comma-separated list of 8-char zero-padded
              company registration numbers to fetch. Non-standard prefixes
              (``SC``, ``NI``, ``OC``, ...) are preserved as-is. Required unless
              ``company_numbers_table`` is set.
            - ``base_url`` (optional): override the default API host.

        Reference-table watchlist (optional, in place of ``company_numbers``):
            - ``company_numbers_table``: fully-qualified UC table name
              (``catalog.schema.table``) with a ``company_number`` string column.
              When set, the watchlist is looked up via the Databricks SQL
              Statement Execution API on every batch instead of being fixed at
              connection-creation time, so users can maintain it by editing the
              table. Requires ``databricks_host``, ``databricks_token``, and
              ``warehouse_id``.
            - ``databricks_host``: workspace URL, e.g. ``https://xxx.cloud.databricks.com``.
            - ``databricks_token``: PAT with SELECT on the table and CAN_USE on the warehouse.
            - ``warehouse_id``: SQL warehouse to run the lookup query on.

        The connector runs inside Spark Python Data Source workers, so it never
        references SparkSession/dbutils (see class docstring); the reference-table
        lookup goes over plain HTTPS via ``requests``, same as the Companies House
        API calls themselves.
        """

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            api_key = options.get("api_key")
            if not api_key:
                raise ValueError("Companies House connector requires 'api_key' in options")
            self._api_key = api_key

            self._base_url = options.get("base_url", BASE_URL).rstrip("/")

            # Resolved lazily (see _get_company_numbers) so a reference-table
            # lookup — if configured — only happens where it's actually needed
            # (get_partitions / read_table, both driver-side), not on every
            # executor instantiation for read_partition.
            self._company_numbers_cache: list[str] | None = None

            # Cap the streaming offset at init time so Trigger.AvailableNow
            # terminates for snapshot tables — see class docstring.
            self._init_time = datetime.now(timezone.utc).isoformat()

        # ------------------------------------------------------------------
        # LakeflowConnect surface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver fallback: iterate all company numbers sequentially.

            Used by ``simpleStreamReader`` when ``is_partitioned`` returns False
            for a table, or by the batch path when partitioning fails. All
            modelled tables are snapshot, so the returned offset is always empty.
            """
            self._validate_table(table_name)

            session = self._build_session()
            try:
                records: list[dict] = []
                for company_number in self._get_company_numbers():
                    records.extend(
                        self._read_records_for_company(
                            table_name, company_number, table_options, session
                        )
                    )
            finally:
                session.close()

            # Snapshot tables — no cursor to advance.
            return iter(records), {}

        # ------------------------------------------------------------------
        # SupportsPartitionedStream surface
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            """All six tables can be partitioned by company_number."""
            return table_name in SUPPORTED_TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return a stable init-time snapshot offset.

            The REST API has no server-side cursor and every table is snapshot,
            so a micro-batch's job is simply to re-read all company numbers
            once. Returning a fixed ``{"snapshot": _init_time}`` means the
            second ``latest_offset`` call in the same trigger sees an
            unchanged value and ``Trigger.AvailableNow`` converges.
            """
            self._validate_table(table_name)
            return {"snapshot": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Yield one partition descriptor per company_number.

            For streaming, when ``start_offset == end_offset`` there is nothing
            new to read (the snapshot has already been drained) — return no
            partitions so the micro-batch is empty.
            """
            self._validate_table(table_name)

            if start_offset is not None and end_offset is not None and start_offset == end_offset:
                return []

            return [
                {"company_number": company_number} for company_number in self._get_company_numbers()
            ]

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Fetch all records for one company_number.

            Runs on Spark executors. Must be self-contained: rebuild the HTTP
            session locally rather than reusing driver state.
            """
            self._validate_table(table_name)
            company_number = partition.get("company_number")
            if not company_number:
                raise ValueError(f"Missing 'company_number' in partition descriptor: {partition!r}")

            session = self._build_session()
            try:
                records = self._read_records_for_company(
                    table_name, company_number, table_options, session
                )
            finally:
                session.close()
            return iter(records)

        # ------------------------------------------------------------------
        # Watchlist resolution (static option or UC reference table)
        # ------------------------------------------------------------------

        def _get_company_numbers(self) -> list[str]:
            """Resolve the company_number watchlist, memoized per instance.

            Prefers ``company_numbers_table`` (a UC reference table users can
            maintain) when set; falls back to the static ``company_numbers``
            option otherwise. Only called from driver-side methods
            (get_partitions / read_table) — never from read_partition — so a
            reference-table lookup runs at most once per batch, not once per
            partition.
            """
            if self._company_numbers_cache is not None:
                return self._company_numbers_cache

            table = self.options.get("company_numbers_table")
            if table:
                numbers = self._fetch_company_numbers_from_table(table)
            else:
                raw = self.options.get("company_numbers", "")
                numbers = [cn.strip() for cn in raw.split(",") if cn.strip()]

            numbers = [
                self._normalize_company_number(cn.strip()) for cn in numbers if cn and cn.strip()
            ]
            if not numbers:
                raise ValueError(
                    "Companies House connector requires either 'company_numbers' "
                    "(comma-separated list) or 'company_numbers_table' "
                    "(a UC table with a company_number column) in options."
                )

            self._company_numbers_cache = numbers
            return numbers

        def _fetch_company_numbers_from_table(self, table: str) -> list[str]:
            """Query a UC reference table for the current watchlist.

            Uses the Databricks SQL Statement Execution API over plain HTTPS —
            the connector never touches SparkSession/dbutils (see class
            docstring), so this is a REST call, not ``spark.table(...)``.
            """
            host = self.options.get("databricks_host")
            token = self.options.get("databricks_token")
            warehouse_id = self.options.get("warehouse_id")
            missing = [
                name
                for name, value in (
                    ("databricks_host", host),
                    ("databricks_token", token),
                    ("warehouse_id", warehouse_id),
                )
                if not value
            ]
            if missing:
                raise ValueError(
                    f"'company_numbers_table' is set but missing required options: {missing}. "
                    "The reference-table watchlist needs 'databricks_host', "
                    "'databricks_token', and 'warehouse_id'."
                )

            host = host.rstrip("/")
            headers = {"Authorization": f"Bearer {token}"}
            session = requests.Session()
            try:
                statement_id = self._submit_sql_statement(session, host, headers, warehouse_id, table)
                return self._collect_sql_statement_results(session, host, headers, statement_id)
            finally:
                session.close()

        def _submit_sql_statement(
            self,
            session: requests.Session,
            host: str,
            headers: dict[str, str],
            warehouse_id: str,
            table: str,
        ) -> str:
            response = session.post(
                f"{host}/api/2.0/sql/statements",
                headers=headers,
                json={
                    "warehouse_id": warehouse_id,
                    "statement": f"SELECT company_number FROM {table}",
                    "wait_timeout": SQL_STATEMENT_WAIT_TIMEOUT,
                },
                timeout=DEFAULT_TIMEOUT_SECONDS,
            )
            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to query company_numbers_table {table!r}: "
                    f"{response.status_code} {response.text}"
                )
            body = response.json()
            return self._await_sql_statement_success(session, host, headers, body)

        def _await_sql_statement_success(
            self,
            session: requests.Session,
            host: str,
            headers: dict[str, str],
            body: dict,
        ) -> str:
            statement_id = body["statement_id"]
            state = body.get("status", {}).get("state")
            for _ in range(SQL_STATEMENT_MAX_POLLS):
                if state == "SUCCEEDED":
                    return statement_id
                if state in ("FAILED", "CANCELED", "CLOSED"):
                    error = body.get("status", {}).get("error", {})
                    raise RuntimeError(
                        f"Query against company_numbers_table failed (state={state}): {error}"
                    )
                time.sleep(SQL_STATEMENT_POLL_SECONDS)
                poll = session.get(
                    f"{host}/api/2.0/sql/statements/{statement_id}",
                    headers=headers,
                    timeout=DEFAULT_TIMEOUT_SECONDS,
                )
                if poll.status_code != 200:
                    raise RuntimeError(
                        f"Failed to poll statement {statement_id}: {poll.status_code} {poll.text}"
                    )
                body = poll.json()
                state = body.get("status", {}).get("state")
            raise RuntimeError(
                f"Timed out waiting for company_numbers_table query {statement_id} to complete"
            )

        def _collect_sql_statement_results(
            self,
            session: requests.Session,
            host: str,
            headers: dict[str, str],
            statement_id: str,
        ) -> list[str]:
            # Re-fetch the statement to get its manifest + first result chunk.
            response = session.get(
                f"{host}/api/2.0/sql/statements/{statement_id}",
                headers=headers,
                timeout=DEFAULT_TIMEOUT_SECONDS,
            )
            if response.status_code != 200:
                raise RuntimeError(
                    f"Failed to fetch results for statement {statement_id}: "
                    f"{response.status_code} {response.text}"
                )
            body = response.json()
            manifest = body.get("manifest", {})
            total_chunks = manifest.get("total_chunk_count", 0)

            numbers: list[str] = []
            result = body.get("result", {})
            numbers.extend(row[0] for row in result.get("data_array", []) if row and row[0])

            for chunk_index in range(1, total_chunks):
                chunk_response = session.get(
                    f"{host}/api/2.0/sql/statements/{statement_id}/result/chunks/{chunk_index}",
                    headers=headers,
                    timeout=DEFAULT_TIMEOUT_SECONDS,
                )
                if chunk_response.status_code != 200:
                    raise RuntimeError(
                        f"Failed to fetch result chunk {chunk_index} for statement "
                        f"{statement_id}: {chunk_response.status_code} {chunk_response.text}"
                    )
                chunk_body = chunk_response.json()
                numbers.extend(row[0] for row in chunk_body.get("data_array", []) if row and row[0])

            return numbers

        # ------------------------------------------------------------------
        # Per-company read dispatch
        # ------------------------------------------------------------------

        def _read_records_for_company(
            self,
            table_name: str,
            company_number: str,
            table_options: dict[str, str],
            session: requests.Session,
        ) -> list[dict]:
            """Route to the right endpoint reader for one company_number.

            Every returned record gets ``_ingested_at`` / ``_ingested_by`` /
            ``_source_api_url`` audit fields stamped on here — a single
            injection point shared by all six tables, rather than repeating it
            in each endpoint reader.
            """
            if table_name == "company_profile":
                records = self._read_single_object(table_name, company_number, table_options, session)
            elif table_name == "registered_office_address":
                records = self._read_single_object(table_name, company_number, table_options, session)
            elif table_name == "charges":
                records = self._read_non_paginated_list(
                    table_name, company_number, table_options, session
                )
            elif table_name in {"officers", "filing_history", "persons_with_significant_control"}:
                records = self._read_paginated_list(table_name, company_number, table_options, session)
            else:
                raise ValueError(f"Unsupported table: {table_name!r}")

            ingested_at = datetime.now(timezone.utc).isoformat()
            # ``pipeline_name`` is a table option a pipeline spec can pass
            # through (must be in the connection's externalOptionsAllowList);
            # falls back to a fixed connector identifier when not supplied.
            ingested_by = table_options.get("pipeline_name") or INGESTED_BY
            source_api_url = f"{self._base_url}{self._format_path(table_name, company_number)}"
            for index, record in enumerate(records):
                record["_ingested_at"] = ingested_at
                record["_ingested_by"] = ingested_by
                record["_source_api_url"] = source_api_url
                # Prefer the API's own resource identifier (links.self); fall
                # back to a positional id so this is *always* unique within one
                # company's fetch, even if the API omits links.self on some
                # items — used as part of the primary key for officers,
                # persons_with_significant_control, and charges (see
                # companies_house_schemas.TABLE_METADATA) because their visible
                # business fields aren't reliably unique.
                links_self = (
                    (record.get("links") or {}).get("self")
                    if isinstance(record.get("links"), dict)
                    else None
                )
                record["_source_record_url"] = links_self or f"{source_api_url}#{index}"
            return records

        # ------------------------------------------------------------------
        # Endpoint readers
        # ------------------------------------------------------------------

        def _read_single_object(
            self,
            table_name: str,
            company_number: str,
            table_options: dict[str, str],
            session: requests.Session,
        ) -> list[dict]:
            """Fetch a single-object endpoint (company_profile / registered_office_address).

            Returns an empty list for HTTP 404 (company not found) so a
            mistyped company_number does not fail the whole batch.
            """
            path = self._format_path(table_name, company_number)
            response = self._request_with_retry(session, "GET", path)
            if response.status_code == 404:
                return []
            if response.status_code != 200:
                raise RuntimeError(
                    f"Companies House API error for {table_name} "
                    f"company={company_number}: {response.status_code} {response.text}"
                )

            body = response.json() or {}
            if not isinstance(body, dict):
                raise ValueError(f"Unexpected response type for {table_name}: {type(body).__name__}")

            record = dict(body)
            # The registered_office_address endpoint does not echo the
            # company_number field — inject it so downstream consumers can
            # join back to company_profile.
            record.setdefault("company_number", company_number)
            return [record]

        def _read_non_paginated_list(
            self,
            table_name: str,
            company_number: str,
            table_options: dict[str, str],
            session: requests.Session,
        ) -> list[dict]:
            """Fetch a list-envelope endpoint that returns all items in one call.

            Used for ``charges``, which has no start_index/items_per_page.
            """
            path = self._format_path(table_name, company_number)
            response = self._request_with_retry(session, "GET", path)
            if response.status_code == 404:
                return []
            if response.status_code != 200:
                raise RuntimeError(
                    f"Companies House API error for {table_name} "
                    f"company={company_number}: {response.status_code} {response.text}"
                )

            body = response.json() or {}
            items = body.get("items") or []
            if not isinstance(items, list):
                raise ValueError(f"Unexpected 'items' type for {table_name}: {type(items).__name__}")

            records: list[dict] = []
            for item in items:
                if not isinstance(item, dict):
                    continue
                record = dict(item)
                # List endpoints don't include the company_number on each item.
                record.setdefault("company_number", company_number)
                records.append(record)
            return records

        def _read_paginated_list(
            self,
            table_name: str,
            company_number: str,
            table_options: dict[str, str],
            session: requests.Session,
        ) -> list[dict]:
            """Fetch an offset-paginated list endpoint (officers / filing_history / PSC).

            Uses ``start_index`` + ``items_per_page``. Advances by the actual
            number of items returned (per API docs — last page can be short).
            Terminates when items is empty or ``start_index >= total_results``.
            """
            path = self._format_path(table_name, company_number)
            items_per_page = self._resolve_items_per_page(table_options)

            records: list[dict] = []
            start_index = 0
            while True:
                params: dict[str, str] = {
                    "start_index": str(start_index),
                    "items_per_page": str(items_per_page),
                }
                # filing_history supports an optional category filter.
                if table_name == "filing_history" and "category" in table_options:
                    params["category"] = table_options["category"]
                # persons_with_significant_control supports optional register_view.
                if (
                    table_name == "persons_with_significant_control"
                    and "register_view" in table_options
                ):
                    params["register_view"] = table_options["register_view"]

                response = self._request_with_retry(session, "GET", path, params=params)
                if response.status_code == 404:
                    return records
                if response.status_code != 200:
                    raise RuntimeError(
                        f"Companies House API error for {table_name} "
                        f"company={company_number}: {response.status_code} {response.text}"
                    )

                body = response.json() or {}
                items = body.get("items") or []
                if not isinstance(items, list):
                    raise ValueError(
                        f"Unexpected 'items' type for {table_name}: {type(items).__name__}"
                    )

                if not items:
                    break

                for item in items:
                    if not isinstance(item, dict):
                        continue
                    record = dict(item)
                    record.setdefault("company_number", company_number)
                    records.append(record)

                # Advance by actual returned length — the last page may be short.
                start_index += len(items)

                # Envelope reports totals under different keys per endpoint:
                #   filing_history → total_count
                #   officers / PSC → total_results
                total = body.get("total_results")
                if total is None:
                    total = body.get("total_count")
                if isinstance(total, int) and start_index >= total:
                    break

                # Defensive: if the API returned fewer than requested, we've
                # hit the tail even without a total.
                if len(items) < items_per_page:
                    break

            return records

        # ------------------------------------------------------------------
        # HTTP plumbing
        # ------------------------------------------------------------------

        def _build_session(self) -> requests.Session:
            """Build a fresh requests.Session with basic-auth pre-configured.

            A new session is created per driver / executor invocation so no
            non-picklable state (Session objects hold sockets) ships across
            the wire.
            """
            session = requests.Session()
            session.auth = (self._api_key, "")
            session.headers.update({"Accept": "application/json"})
            return session

        def _request_with_retry(
            self,
            session: requests.Session,
            method: str,
            path: str,
            params: dict | None = None,
        ) -> requests.Response:
            """Issue an HTTP request with exponential backoff on retriable statuses.

            Honours the ``Retry-After`` header on 429 responses when present;
            otherwise falls back to exponential backoff.
            """
            url = f"{self._base_url}{path}"
            backoff = INITIAL_BACKOFF_SECONDS
            last_response: requests.Response | None = None
            for attempt in range(MAX_RETRIES):
                response = session.request(method, url, params=params, timeout=DEFAULT_TIMEOUT_SECONDS)
                last_response = response
                if response.status_code not in RETRIABLE_STATUS_CODES:
                    return response

                if attempt == MAX_RETRIES - 1:
                    break

                # Respect Retry-After when the server provides it.
                retry_after = response.headers.get("Retry-After")
                delay = backoff
                if retry_after:
                    try:
                        delay = max(delay, float(retry_after))
                    except (TypeError, ValueError):
                        pass
                time.sleep(delay)
                backoff *= 2

            assert last_response is not None  # loop always assigns
            return last_response

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table {table_name!r} is not supported. Supported tables: {list(SUPPORTED_TABLES)}"
                )

        def _format_path(self, table_name: str, company_number: str) -> str:
            template = TABLE_ENDPOINT_PATHS[table_name]
            return template.format(company_number=company_number)

        def _resolve_items_per_page(self, table_options: dict[str, str]) -> int:
            raw = table_options.get("items_per_page")
            if raw is None:
                return DEFAULT_ITEMS_PER_PAGE
            try:
                v = int(raw)
            except (TypeError, ValueError):
                return DEFAULT_ITEMS_PER_PAGE
            # API max is 100.
            return max(1, min(v, 100))

        @staticmethod
        def _normalize_company_number(company_number: str) -> str:
            """Zero-pad numeric company numbers to 8 chars; preserve alpha prefixes.

            Companies House registration numbers are 8 characters. Purely
            numeric numbers (e.g. ``6``) get zero-padded to ``00000006``.
            Numbers with alpha prefixes (``SC``, ``NI``, ``OC``, ``SO``,
            ``IP``, ``IC``, ``R0``) are left as-is because the pad rule is
            different for each prefix and the caller typically already
            supplies them padded.
            """
            if not company_number:
                return company_number
            if company_number.isdigit():
                return company_number.zfill(8)
            return company_number


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = CompaniesHouseLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
